### ISSUE TITLE
Using the provided materials create Valve device class based on the facadedevice library.

### ISSUE THREAD

**Issue by wkitka** [synchrotron-solaris/dev-solaris-valve#1]
Properties:
- [x] PlcAttrName_CloseC
- [x] PlcAttrName_ClosedS
- [x] PlcAttrName_OpenC
- [x] PlcAttrName_OpenS
- [x] PlcAttrName_InterlockA
- [x] PlcAttrName_CutOffA
- [x] PlcAttrName_UnexpectedState

Attributes:
- [x] ValveOpen: PlcAttrName_OpenS readout.
- [x] ValveClosed: PlcAttrName_CloseC readout.
- [x] ValveInterlock: PlcAttrName_InterlockA readout.
- [x] ValveCutOff: PlcAttrName_CutOffA readout.
- [x] UnexpectedState: PlcAttrName_UnexpectedState readout.

Commands:
- [x] Open: write True to PlcAttrName_OpenC.
- [x] Close: write True to PlcAttrName_CloseC.

**Comment by LJBD** [comment]
How to run a server with more than 1 class:

```python
from tango.server import Device, run

class FirstDevice(Device):
    pass

class SecondDevice(Device):
    pass

run({"FirstDevice": FirstDevice, "SecondDevice": SecondDevice}, *args, **kwargs)

```

**Comment by LJBD** [comment]
The complete & tested version of launching a Device Server with 2 or more Device Classes is [here](https://github.com/LJBD/lib-tango-sample-device).

**Comment by stanislaw47** [comment]
@LJBD 
Shoud I add `state_attribute` to handle state changes, like `OPEN`, `CLOSED` or `ALARM` in case of interlock, etc? Or is it handled by PLC?

**Comment by LJBD** [comment]
@stanislaw47 - you should add it, PLC cannot directly influence a state of a Tango Device.
